<%-- 
    Document   : registrationproccess
    Created on : Apr 18, 2018, 2:06:20 PM
    Author     : Ian
--%>

<%
    java.sql.Connection conn;                 // Connection: A connection with a specific database.
    java.sql.ResultSet rs, rs1;                   // ResultSet: A table of data representing a database result set, which is usually generated by executing a statement that queries the database. 
    java.sql.Statement st,st1, st2;               // Statement: The object used for executing a static SQL statement and returning the results it produces.
    // mysql database to work with your project. Go to,
    // Your project -> right click -> properties -> Libraries -> Compiler tab -> Add library -> select "MySQL JDBC Driver" library -> Ok
    Class.forName("com.mysql.jdbc.Driver"); //to connect mysql database
    conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/comp6000", "comp6000", "comp6000");  //connection with database.. demo: db name, username:root, password: " "
    st = conn.createStatement();
    st1 = conn.createStatement();
    st2 = conn.createStatement();

    //get parameter value by using the 'name' of the field
    String email = request.getParameter("email");    
    String username = request.getParameter("username");     
    String password = request.getParameter("password");

    String qr = "SELECT username FROM users WHERE username = '"+username+"'";    //query to select if the username already exists or not
    rs = st.executeQuery(qr);
    if(rs.next())                       
    {
        // lets say "a" is for "user already exists" // passing variable "a" with URL
        response.sendRedirect("index.jsp?a");                                    // if username found in database, redirect user to index.jsp with some error
    }
    else
    {
        String sql = "INSERT INTO users (username, password, email) values ('"+username+"', '"+password+"', '"+email+"')";   //query to enter values in database
        st1.executeUpdate(sql);
        response.sendRedirect("loginValidation?username="+username+"");  
    }
    
%>